"""add car table

Revision ID: 09ae9986ef46
Revises: ef1f7bd432fb
Create Date: 2023-01-19 10:45:50.828052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ae9986ef46'
down_revision = 'ef1f7bd432fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('objectId', sa.String(length=25), nullable=False),
    sa.Column('createdAt', sa.String(length=25), nullable=False),
    sa.Column('updatedAt', sa.String(length=25), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('make', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###