"""user and car table

Revision ID: ef1f7bd432fb
Revises: 0ad50c9efaa2
Create Date: 2023-01-12 06:34:40.844779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef1f7bd432fb'
down_revision = '0ad50c9efaa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('objectId', sa.String(length=25), nullable=False),
    sa.Column('createdAt', sa.String(length=25), nullable=False),
    sa.Column('updatedAt', sa.String(length=25), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('make', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    op.drop_table('car')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('objectId', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('createdAt', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('updatedAt', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('make', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('cars')
    # ### end Alembic commands ###